### ISSUE TITLE
Blank gray screen with no interface after update

### ISSUE THREAD

**Issue by Asgarda** [nextcloud/richdocuments#115]
Greetings!

I'm trying to test new Nextcloud with new Collabora-Online, and i've recieves unexpected results...
My apache configuration is right and no errors in any log files. Collabora/CODE admin console works properly. I think what something wrong with NC Collabora aplication =/

### Steps to reproduce
1. Create two LXC containers with Debian 8 and Ubuntu 16.04 in Proxmox VE
2. Install fresh Nextcloud to Debian CT and Collabora/CODE on Ubuntu (without Docker, native packages) CT, we need something like two different servers - NC and CODE
3. Configure apache for it
4. Try to use it

### Expected behaviour
After enabling Collabora Online app in Nextcloud, we shoud get document editing form, like LibreOffice

### Actual behaviour
After enabling Collabora Online app in Nextcloud, we gets gray screen and NC bar at the top of page like...
![screenshot - 08212017 - 09 59 38 am](https://user-images.githubusercontent.com/31200890/29507165-9955ab62-8657-11e7-9f90-5775b03bc6b7.png)

### Server configuration

Proxmox VE 4.4

**Operating system**: 
1) LXC Debian 8 CT template for Nextcloud
2) LXC Ubuntu 16.04 CT template for Collabora/CODE

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.6

**PHP version:** PHP 7

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install, downloaded from nextcloud.com

**Where did you install Nextcloud from:** manual, by Nexcloud installation guide from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocfde7y09tqj",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud0.mycompany.com"
        ],
        "datadirectory": "\/var\/www\/cloud0.mycompany.com\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud0.mycompany.com",
        "dbtype": "pgsql",
        "version": "12.0.2.0",
        "dbname": "ncbase",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no, local folders, just for test

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  no

### Client configuration
**Browser:** Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.6 (64-bit)

**Operating system:** Debian 8.6 Jessie (64-bit)

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ShortnStubby** [comment]
Has there been any resolution to this? Currently encountering the same issue. Thanks

**Comment by Krautmaster** [comment]
alwaysa had this issue updating my docker with collabora online in nextcloud - only grey screen. I found it to be fixed once i simply switched to nextcloud settings in webgui, collabora online menu, store the same stuff without changes again and it should work directly. :)
Collabora Online -> Collabora Online Server (URL)

**Comment by AndrinS** [comment]
I just found the following fix, which is easier to do than pressing the apply button (at least if you host multiple Nextcloud instances). Same fix works for ownCloud.

Delete the following file in your Nextcloud webroot: 

`rm data/appdata_*/richdocuments/richdocuments/discovery.xml`

(* because of randomly generated string)

The file seems to contain cached information about the collabora server. It's automatically generated as soon as someone access a file.

**Comment by thebearon** [comment]
This issue is fixed in 3.3.

**Comment by danger89** [comment]
Which issue exactly? Since this issue does not describe any **root cause**. Nor any log file of Collabora Online/LibreOffice Online.

So what is actually really fixed?

The gray screen you are seeing is a side affect. Please bear in mind this reported issue is very vague. There are different kind of root causes, resulting in this gray screen.

Like:
- wrong Nginx reverse proxy config (both Nextcloud or Collabora)
- Misconfigured LibreOffice config (= loolwsd.xml file).
- Docker instance problems, you name it..
- ....
- ...

**Comment by danger89** [comment]
> 
> 
> This issue is fixed in 3.3.

version 3.3 of what? Richdocuments? I only see v.3.2.1 released or master branch :confused:

**Comment by danger89** [comment]
I still have issues with this "block gray screen". Nextcloud v15.0.4. Richdocuments v3.2.1. LibreOffice v6.3.

Using both Libreoffice online/Collabora and Nextcloud behind Nginx reverse web proxy.


Libreoffice Online docker log output:
```
wsd-00015-00023 2019-02-26 18:04:26.356688 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:16.300652 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache.| wsd/FileServer.cpp:279                                                         
wsd-00015-00023 2019-02-26 18:05:16.420838 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:16.647657 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:24.485582 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache.| wsd/FileServer.cpp:279                                                         
wsd-00015-00023 2019-02-26 18:05:24.620217 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:24.813640 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:25.868642 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache.| wsd/FileServer.cpp:279                                                         
wsd-00015-00023 2019-02-26 18:05:26.018280 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:26.212475 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
```

**Comment by thebearon** [comment]
> version 3.3 of what? Richdocuments? I only see v.3.2.1 released or master branch confused

Obviously not richdocuments, then, especially considering this issue got closed half a year ago. Collabora Online 3.3.

The issue here was that Nextcloud caches the content of Collabora Online's discovery.xml, and the handler URIs contain the commit hash of the online build, thus after an upgrade of Collabora Online, richdocuments still tried to access it via the old URIs. This is definitely fixed: while the hash is still in the URI, Collabora Online will respond the same regardless of the hash.

Please don't spam random old **closed** tickets with your problem, just open a new one if you think there's a bug, or head over to https://help.nextcloud.com/ for support.

Btw, the logs above don't indicate any problems, the missing file indication is related to missing branding, which is optional, and the version mismatch could be because of the same reason as I described above.
