### ISSUE TITLE
Watermarking not working

### ISSUE THREAD

**Issue by WindfallProphet** [nextcloud/richdocuments#1151]
**Describe the bug**
Enabled watermark, but no watermark present.

**To Reproduce**
1. Enable Watermarking

**Expected behavior**
Expected to see watermark on documents

**Client details:**
 - OS: Arch Linux
 - Browser Firefox
 - Version  80.1
 - Device: x64 deskdop

## Server details
**Operating system**:
Centos 8 x86_64
**Web server:**
nginx/1.14.1
**Database:**
mysql v.15.1 -10.3.17-mariadb
**PHP version:**
php 7.4.10 
Modules [php]: apcu, bcmath, bz2, calendar, Core, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, session, shmop, SimpleXML, sockets, sodium, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, Zend OPcache, zip, zlib
**Nextcloud version:**
Nextcloud 19.0.2
**Version of the richdocuments app**
3.7.4
**Version of Collabora Online**
4.2.6-2

<details>
<summary>Logs</summary>
"message":"Undefined index: watermark_{text,allTags,allGroups,linkTags,linkAll,linkRead,linkSecure,shareRead,enabled} at /var/www/nextcloud/apps/richdocuments/lib/Controller/SettingsController.php#237","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"19.0.2.2","id":"5f596d10c293c"}
</details>

**Comment by WindfallProphet** [comment]
Might be a Duplicate of #911

**Comment by juliushaertl** [comment]
Thanks for reporting, I'm not sure where or how this broke but https://github.com/nextcloud/richdocuments/pull/1152 should fix it, testing and review are very welcome

**Comment by WindfallProphet** [comment]
I'm getting no more watermark complaints in nextcloud.log, but I'm unable to view a file anonymously. I would have sworn this was working, but both pre and post #1152 are having the same issue. 

Watermarking disabled → anonymous browsing works
Watermarking enabled → anonymous browsing results in a loading loop with the following in the browser log 

<details>
<summary>Logs </summary>
#### Chrome v85.0.4183.102 logs

```javascript
Uncaught (in promise) TypeError: Cannot read property 'fileList' of undefined
    at 3.js:65
    at Module.29 (3.js:65)
    at o (files.js?v=ff7d3fcb-3:1)
EfAtnWEt4KLPKpJ:1 Failed to load resource: the server responded with a status of 404 ()
files.js?v=ff7d3fcb-3:44 Uncaught TypeError: Cannot read property 'insertBefore' of null
    at Object.initAfterReady (files.js?v=ff7d3fcb-3:44)
    at Object.onReceiveLoading (files.js?v=ff7d3fcb-3:44)
    at files.js?v=ff7d3fcb-3:44
    at files.js?v=ff7d3fcb-3:44
    at Array.forEach (<anonymous>)
    at e.value (files.js?v=ff7d3fcb-3:44)
    at files.js?v=ff7d3fcb-3:44
bundle.js:39 Blocked autofocusing on a <textarea> element in a cross-origin subframe.
onAdd @ bundle.js:39
232:1

```
</detail>

The only big change I did was update from php:7.2 to remi-php:7.4 on Centos 8, but maybe the update affected it?

**Comment by WindfallProphet** [comment]
Also, I'm not seeing any watermarks on the file when I enable them. I thought that maybe it had something to do with me being logged in, so I logged out and noticed the above issue. 

Those maybe entirely new issue(s), but I don't want to unnecessarily open new issues. I'm no longer getting the watermark error in the Nextcloud logs, but watermarking still isn't working.

**Comment by juliushaertl** [comment]
Maybe you can share your exact watermarking settings that you have configured?

**Comment by WindfallProphet** [comment]
Sorry I'm running behind. 

![firefox_wZkTjOcexm](https://user-images.githubusercontent.com/11915275/95700911-28e76800-0c16-11eb-8030-a5d0a030bf97.png)

Any ideas? Not sure if it's a backend or frontend problem.

**Comment by WindfallProphet** [comment]
This is making me think it's backend, but it only presents when I enable watermarking.

```
Backtrace 423634:
/usr/bin/loolforkit(_ZN7SigUtil13dumpBacktraceEv+0x62)[0x55eb0fea7a42]
/usr/bin/loolforkit(+0x205fdd)[0x55eb0fea7fdd]
/lib64/libpthread.so.0(+0x12dd0)[0x7f5d7e06ddd0]
/lib64/libc.so.6(gsignal+0x10f)[0x7f5d7dcd070f]
/lib64/libc.so.6(abort+0x127)[0x7f5d7dcbab25]
/usr/bin/loolforkit(+0x194ec8)[0x55eb0fe36ec8]
/usr/bin/loolforkit(_ZN9Watermark9getPixmapEii+0x8dd)[0x55eb0fe651dd]
/usr/bin/loolforkit(_ZNSt17_Function_handlerIFvPhiimmii22LibreOfficeKitTileModeEZN8Document11renderTilesER12TileCombinedbEUlS0_iimmiiS1_E_E9_M_invokeERKSt9_Any_dataOS0_OiSC_OmSD_SC_SC_OS1_+0x9d)[0x55eb0fe6539d]
/usr/bin/loolforkit(_ZN11RenderTiles8doRenderESt10shared_ptrIN3lok8DocumentEER12TileCombinedR8PngCacheR10ThreadPoolbRKSt8functionIFvPhiimmii22LibreOfficeKitTileModeEERKSA_IFvPKcmEE+0x599)[0x55eb0fe52ac9]
/usr/bin/loolforkit(_ZN8Document11renderTilesER12TileCombinedb+0x202)[0x55eb0fe74b02]
/usr/bin/loolforkit(_ZN8Document10drainQueueERKNSt6chrono10time_pointINS0_3_V212steady_clockENS0_8durationIlSt5ratioILl1ELl1000000000EEEEEE+0x364)[0x55eb0fe754d4]
/usr/bin/loolforkit(_ZN13KitSocketPoll7kitPollEi+0x2c1)[0x55eb0fe77601]
/opt/collaboraoffice6.4/program/libmergedlo.so(_ZN14SvpSalInstance7DoYieldEbb+0x112)[0x7f5d7b63f792]
/opt/collaboraoffice6.4/program/libmergedlo.so(+0x2f852db)[0x7f5d7b5882db]
/opt/collaboraoffice6.4/program/libmergedlo.so(_ZN11Application7ExecuteEv+0x45)[0x7f5d7b588e75]
/opt/collaboraoffice6.4/program/libmergedlo.so(+0x1f94905)[0x7f5d7a597905]
/opt/collaboraoffice6.4/program/libmergedlo.so(_Z10ImplSVMainv+0x51)[0x7f5d7b58ff01]
/opt/collaboraoffice6.4/program/libmergedlo.so(soffice_main+0x98)[0x7f5d7a5b8f48]
/opt/collaboraoffice6.4/program/libmergedlo.so(+0x1fc5b81)[0x7f5d7a5c8b81]
/usr/bin/loolforkit(_Z10lokit_mainRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_S6_S6_bbbbm+0x1f60)[0x55eb0fe57990]
/usr/bin/loolforkit(+0x1a008c)[0x55eb0fe4208c]
/usr/bin/loolforkit(_Z18forkLibreOfficeKitRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_S6_i+0x8a4)[0x55eb0fe42d64]
/usr/bin/loolforkit(main+0x185c)[0x55eb0fe0fefc]
/lib64/libc.so.6(__libc_start_main+0xf3)[0x7f5d7dcbc6a3]
/usr/bin/loolforkit(_start+0x2e)[0x55eb0fe161ee]
wsd-423563-423646 2020-10-12 03:23:33.899476 [ docbroker_004 ] ERR  No DocBroker found, or DocBroker marked to be destroyed. Terminating session ToClient-00a| wsd/ClientSession.cpp:331
kit-423647-423575 2020-10-12 03:23:37.183674 [ kitbroker_005 ] SIG   Fatal signal received: SIGABRT
```

**Comment by juliushaertl** [comment]
Seems like it, maybe report an issue upstream at https://github.com/collaboraonline/online
