### ISSUE TITLE
Document not loading - TypeError: fileName is undefined

### ISSUE THREAD

**Issue by himpierre** [nextcloud/richdocuments#2017]
**Describe the bug**
When opening a document, collabora loads but the document area stays empty.

**To Reproduce**
1. Open a document (does not matter if docx or odt)
2. collabora loads but document area stays empty

**Expected behavior**
Document loads completely.

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 96

## Server details

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0.15

**Nextcloud version:** 23.0.1

**Version of the richdocuments app** 5.0.1

**Version of Collabora Online** 21.06.13-1

#### Browser log (data/nextcloud.log is empty)
```
Error during post message handler 
Object { msgId: "App_LoadingStatus", args: {…}, deprecated: false }
 TypeError: fileName is undefined
    getModelForFile merged-index.js:4636
    getFileModel FilesAppIntegration.js:190
    initAfterReady FilesAppIntegration.js:80
    postMessageHandler Office.vue:224
    handlePostMessage postMessage.tsx:115
    handlePostMessage postMessage.tsx:109
    v postMessage.tsx:45
    v postMessage.tsx:44
    <anonymous> Office.vue:82
    <anonymous> viewer.js:36
    <anonymous> viewer.js:36
[postMessage.tsx:120:12](webpack:///richdocuments/src/services/postMessage.tsx)
[viewer] Received post message 
Object { msgId: "Action_Load_Resp", args: {…}, deprecated: false }
[Office.vue:214](webpack:///richdocuments/src/view/Office.vue)
Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null
    _hideWizard https://office.domain.de/browser/739da71/bundle.js:1
    onAdd https://office.domain.de/browser/739da71/bundle.js:1
    addControl https://office.domain.de/browser/739da71/bundle.js:1
    initializeBasicUI https://office.domain.de/browser/739da71/bundle.js:1
    <anonymous> https://office.domain.de/browser/739da71/bundle.js:1
    <anonymous> https://office.domain.de/browser/739da71/bundle.js:1
    <anonymous> https://office.domain.de/browser/739da71/bundle.js:1
[bundle.js:1:2260334](https://office.domain.de/browser/739da71/bundle.js)
[viewer] Received post message 
Object { msgId: "Action_Load_Resp", args: {…}, deprecated: false }
[Office.vue:214](webpack:///richdocuments/src/view/Office.vue)
[viewer] Received post message 
Object { msgId: "Views_List", args: (1) […], deprecated: false }
[Office.vue:214](webpack:///richdocuments/src/view/Office.vue)
[viewer] Received post message 
Object { msgId: "Doc_ModifiedStatus", args: {…}, deprecated: false }
[Office.vue:214](webpack:///richdocuments/src/view/Office.vue)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 [globals.js:62:15](webpack:///core/src/globals.js)
No new notification data received [App.vue:294](webpack:///notifications/src/App.vue)
Polling interval updated to 30000 [App.vue:326](webpack:///notifications/src/App.vue)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 16 [util.js:135:11](webpack:///core/src/OC/util.js)

​
```

**Comment by Chiller2019** [comment]
same here

**Comment by mneiger** [comment]
likely same here 
Works well with  CHrome / Chromium /Opera but problem with firefox 96.0.3 on linux clients

Server details
Operating system: Linux Mint 20.3
Web server: Nginx
Database: MariaDB
PHP version: 7.4.3
Nextcloud version: 23.0.0
Version of the Collabora Online App 5.0.1
Version of Collabora Online 21.11.1.4-1

**Comment by danir-de** [comment]
We have identified the same problem on Firefox ESR 91.6 and Stable 98.0 (both Windows). Since this happens every second time you open a document in Collabora, this bug is breaking the functionality for Firefox users.

**Comment by yodatak** [comment]
Same for us with firefox
With nextcloud 23.0.2
And 
COOLWSD
21.11.1.4 (git hash: [739da71](https://github.com/CollaboraOnline/online/commits/739da71))
LOKit
Collabora Office 21.06.13.1 (git hash: [242d275](https://hub.libreoffice.org/git-core/242d275))

**Comment by himpierre** [comment]
Another observation. Seems to be a problem of nextcloud 23.0.0 and above. No problems with a nextcloud 22.2.5 installation.

**Comment by himpierre** [comment]
Fixed with 5.0.3? A few short tests show no problems anymore.

**Comment by juliushaertl** [comment]
Thanks for the update. The error message `Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null` is indeed something that could have happened with 21.11.1.4 (git hash: [739da71](https://github.com/CollaboraOnline/online/commits/739da71)) and should have been fixed with the latest collabora release.

**Comment by Wikinaut** [comment]
@juliushaertl I still have on one of my instances this load error message, but have no idea, how I could find the problem. This instance does also _not_ load an external Collabora Servivce.

Pls. can you assist? I am willing to look for the problem and to help to fix it!

* NC 23.0.2
* Nextcloud Office 5.0.3
* Collabora Online -Built-inServer CODE 21.11.204
* 
![grafik](https://user-images.githubusercontent.com/1151915/156881566-1207809b-6fcb-401c-ab09-2d0616f67f08.png)

**Comment by Wikinaut** [comment]
I also notice, that sometimes I see this 
![grafik](https://user-images.githubusercontent.com/1151915/156881909-0d8a4244-b044-4364-afd1-1bac1cd4d540.png)
sometimes it tries to start the Collabora.

What the heck it happening there?

Can this be a problem from too low CPU/process memory?

**Comment by himpierre** [comment]
@juliushaertl Could you please reopen this issue? Giving the all-clear was obviously a bit premature. Problem still exists.

**Comment by himpierre** [comment]
Strange thing is when I'm not logged in to my nextcloud and click on a shared link of a document, the very same docx file opens. When logged in it doesn't. Someone else experiences this?

**Comment by aov-arnold** [comment]
We still have the problem with NC 23.0.2.1 and Collabora Code 21.11.2.4.1. Both docker containers.
NC Office is version 5.0.3. Firefox Version is 91.6.0esr.

**Error 1:**
![grafik](https://user-images.githubusercontent.com/57179682/158175929-9fbd7e93-52fd-4bde-8e7f-5940f670a23d.png)

**Error 2:**
![grafik](https://user-images.githubusercontent.com/57179682/158175820-09da47b9-0911-4fd6-977a-1476f451f39e.png)

**Comment by aov-arnold** [comment]
Especially we can't access a document with firefox when there is already somebody editing.
It's working with chrome.

**Comment by aov-arnold** [comment]
@jeensg The Hotfix in #2094 seems to fix it partially. However the Firefox problem with multiple users editing one document remains.

**Comment by yodatak** [comment]
Same problem again for me

**Comment by danir-de** [comment]
The `Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null`-problem now has it's own issue, since it still is a problem: #2125
