### ISSUE TITLE
`FilesAppIntegration.getFileModel` causes "TypeError: fileName is undefined"

### ISSUE THREAD

**Issue by msebas** [nextcloud/richdocuments#2094]
Hello,

yesterday I updated 
Nextcloud to 23.0.2 (docker container)
DB: Mariadb
Reverseproxy: nginx

Alongside I installed
Collabora: 21.11.2.4.1
Richtdocuments: 5.0.3

Everything runs in one docker-compose setup.

When I tried to open a freshly created document I got the error message 
```
Error during post message handler 
Object { msgId: "App_LoadingStatus", args: {…}, deprecated: false }
 TypeError: fileName is undefined
    getModelForFile merged-index.js:4636
    getFileModel FilesAppIntegration.js:190
    initAfterReady FilesAppIntegration.js:80
    postMessageHandler Office.vue:231
    handlePostMessage postMessage.tsx:115
    handlePostMessage postMessage.tsx:109
    C postMessage.tsx:45
postMessage.tsx:120:12
```

I took al look to `FilesAppIntegration.getFileModel:190` and there the line is
`if (!this.getFileList() || !this.getFileList()?.getModelForFile() || !this.getFileList()._updateDetailsView) {`

I fixed this assuming that `getModelForFile` needs the current file name to get
`if (!this.getFileList() || !this.getFileList()?.getModelForFile(this.fileName) || !this.getFileList()._updateDetailsView) {`
rebuild and reinstalled the app and then the editor started working fine.

I was unable to find any other case in the repositories where `getModelForFile` does not take an argument, so I just wanted to report this in case it is a real bug. 

Kind regards

**Comment by msebas** [comment]
Well, at least line 190 was not changed from 5.01 to 5.03. 
@aov-arnold: Are you able to build the app from source? If yes I would like to ask you to check if 
https://github.com/msebas/richdocuments/tree/fix%232094 
resolves the problem (the first one, the second one, with the `app.sectionContainer.getSectionWithName(...) is null` in the error message appearing when multiple people edit the same file.). If yes I could turn the branch into a pull request to get the bug fixed in the next version.

**Comment by aov-arnold** [comment]
@msebas I will try tomorrow! 
**Like that?**
- uninstall NC office
- clone your repo to apps directory
- install Node.js and npm in docker container
- run npm ci and npm run dev

**Comment by aov-arnold** [comment]
After setting the Nextcloud min version to 23 I could activate the app.
The Editor is still not loading but the error in the GUI and the "fileName is undefined" error in the console are gone.

**Comment by msebas** [comment]
@aov-arnold:
You build the app by doing the first 3 steps as given by you, and then
* run `git checkout fix#2094` (if not already done)
* run `npm ci`
* run `npm run build` (this creates a `js` directory missing in the repository)

Setting Nextcloud min Version to  23? Sounds like you used the master (the fix is on branch fix#2094, which could be checked out using `git checkout fix#2094` from the git shell). Could you please check that? 
If it still does not work please check you browser log for a follow up error. I cannot promise to fix it, but I am at least going to take a look.

PS:
If you run `npm run dev` you are using the development server which is great for debugging (vue) and hot reload, but require that you set up some other stuff (at least in my projects).

**Comment by aov-arnold** [comment]
@msebas
Sorry for the delay and thank you for the instructions!

I have now tested it with fix#2094. It looks good regarding the first problem. As you said the second firefox problem with multiple users in the same document ist not fixed.

**Comment by himpierre** [comment]
@msebas The branch fix#2094 already gone? Just tried to checkout without success. Cheers!

**Comment by himpierre** [comment]
@msebas nvm. it's in another repo. :)

**Comment by msebas** [comment]
@aov-arnold Thx for the update. As I said the other one seems to be in collabora online, but I do not know where or what exactly is happening, but it might be a good idea to look into https://github.com/CollaboraOnline/online/issues/4264 , which has a similar error message, but I do not know if it fixes the problem.

@himpierre: Please report if it resolves the error. I would like to turn the fix into a pull request.

**Comment by himpierre** [comment]
I'll wait for the MR. :)

Am 19. März 2022 13:46:29 MEZ schrieb msebas ***@***.***>:
***@***.*** Thx for the update. As I said the other one seems to be in collabora online, but I do not know where or what exactly is happening, but it might be a good idea to look into https://github.com/CollaboraOnline/online/issues/4264 , which has a similar error message, but I do not know if it fixes the problem.
>
***@***.***: Please report if it resolves the error. I would like to turn the fix into a pull request.
>

**Comment by himpierre** [comment]
Did someone test 6.0.0 beta1? Also is this bug really affecting all firefox users? If so, there should be a much more louder cry for help. :)

**Comment by himpierre** [comment]
I took the time today to try to solve the problem for myself. Uninstalled richdocuments, cleared the nextcloud database, re-installed richdocuments. Same problem. Switched to integrated code server. Works. Switched to another self-hosted collabora installation. To my surprise that worked too. So my guess is my self-hosted collabora installation was somewhat faulty. I just leave it at that for now.

**Comment by himpierre** [comment]
Aiee! Found the problem on my side. Nextcloud installation and Collabora installation shared the same toplevel domain. It was mydomain.org for nextcloud and office.mydomain.org for Collabora. After re-configuring Collabora to use office.anotherdomain.org everything worked. Maybe I skrewed my apache config and could have done that easier but it was clearly a domain issue here.

**Comment by XueSheng-GIT** [comment]
> After re-configuring Collabora to use office.anotherdomain.org everything worked.

Can you elaborate how you configured this?

**Comment by himpierre** [comment]
Well not collabora itself. I meant the apache vhost who is proxying the requests to collabora.

Am 1. Mai 2022 12:33:12 MESZ schrieb XueSheng-GIT ***@***.***>:
>> After re-configuring Collabora to use office.anotherdomain.org everything worked.
>
>Can you elaborate how you configured this?
>

**Comment by juliushaertl** [comment]
Addressed by #2187 but underlying issue will be fixed by #2212
