### ISSUE TITLE
Can't open office documents after update to NC 26

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#2873]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I can use Office in the mobile Browser, but it do not load any more in the android app.
Before the update to 26 it was working.
Tried with 2 different phones. 

I tried with this 2 possibilities:
![grafik](https://user-images.githubusercontent.com/24530680/226910686-f411db15-40cb-4d9d-a1eb-f254123746f0.png)

### Expected behaviour

open the file

### Actual behaviour

![grafik](https://user-images.githubusercontent.com/24530680/226910342-d212577e-4d4a-4903-825f-8cd49a92a5ec.png)

### Android version

13

### Device brand and model

Pixel 4a (5G)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.1

### Nextcloud server version

26

### Using a reverse proxy?

I don't know

**Comment by jakobroehrl** [comment]
> Another user saw on iOS that there is a dialog to enter a guest user name. This seems to block Android.
I can confirm this, same for me with ios.
Thanks for caring

**Comment by juliushaertl** [comment]
I can reproduce but not sure what causes this yet. I don't recall any related change. Looking into it

**Comment by Happyfeet01** [comment]
i have the same issue with Nextcloud Office after updating to NC 26.

Got this message in the Logs:

Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php#132

the

**Comment by davidwuest** [comment]
Same issue. Checked all other options. It is the richdocuments plugin causing the problem.

**Comment by r4tt4** [comment]
I also can confirm this issue after upgrading to NC26. 
Open a document in Android NC App will stuck in "das Laden dauert sehr lange...".
Using a mobile webbrowser with NC, document gets loaded w/o any problems.
Hope there will be a fix soon...

**Comment by G-T100** [comment]
Asks for nick name when opening or creating a document iOS

‘Please choose your nickname to continue as guest user’

Opening documents desktop browser works well.

Cannot find any error logs.

Tested, iphone 6s and iphone 13.

NC 26.0 and latest apps versions.

**Comment by LokeYourLord** [comment]
Same issue for me. Opening documents in the mobile app doesn't work and loads forever on Android, while Browser works just fine (Collabora CODE self-hosted). Nothing really in the logs when I try opening one of these documents, but I get this sometimes when opening documents:

```
[richdocuments] Error: GuzzleHttp\Exception\ServerException: Server error: `GET https://office.xx.xx/hosting/capabilities` resulted in a `500 Internal Server Error` response:
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
 (truncated...)
 at <<closure>>

 0. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 69
    GuzzleHttp\Exception\RequestException::create("*** sensitive parameters replaced ***")
 1. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 204
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 153
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 3. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 48
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 248
    GuzzleHttp\Promise\TaskQueue->run(true)
 5. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 224
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 269
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 226
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /home/sysadmin/web/**REDACTED**/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Promise\Promise->wait()
10. /home/sysadmin/web/**REDACTED**/public_html/lib/private/Http/Client/Client.php line 226
    GuzzleHttp\Client->request("get", "https://office. ... s", ["/home/sysadmin ... e])
11. /home/sysadmin/web/**REDACTED**/public_html/apps/richdocuments/lib/Service/CapabilitiesService.php line 135
    OC\Http\Client\Client->get("https://office. ... s", [45,[true]])
12. /home/sysadmin/web/**REDACTED**/public_html/apps/richdocuments/lib/Service/CapabilitiesService.php line 73
    OCA\Richdocuments\Service\CapabilitiesService->refetch()
13. /home/sysadmin/web/**REDACTED**/public_html/apps/richdocuments/lib/AppInfo/Application.php line 80
    OCA\Richdocuments\Service\CapabilitiesService->getCapabilities()
14. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 66
    OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensitive parameters replaced ***")
15. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/Bootstrap/BootContext.php line 50
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn(["Closure"])
16. /home/sysadmin/web/**REDACTED**/public_html/apps/richdocuments/lib/AppInfo/Application.php line 135
    OC\AppFramework\Bootstrap\BootContext->injectFn(["Closure"])
17. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/Bootstrap/Coordinator.php line 200
    OCA\Richdocuments\AppInfo\Application->boot(["OC\\AppFramewo ... "])
18. /home/sysadmin/web/**REDACTED**/public_html/lib/private/legacy/OC_App.php line 213
    OC\AppFramework\Bootstrap\Coordinator->bootApp("richdocuments")
19. /home/sysadmin/web/**REDACTED**/public_html/lib/private/legacy/OC_App.php line 141
    OC_App::loadApp("richdocuments")
20. /home/sysadmin/web/**REDACTED**/public_html/ocs/v1.php line 57
    OC_App::loadApps()
21. /home/sysadmin/web/**REDACTED**/public_html/ocs/v2.php line 23
    require_once("/home/sysadmin/ ... p")

GET /ocs/v2.php/apps/activity/api/v2/activity/by
from xxx.xxx.xxx.xxx by sysadmin at 2023-04-10T05:13:31+00:00
```

And this one came up once:

```
[richdocuments] Error: OCA\Richdocuments\Exceptions\UnknownTokenException: Could not find token. at <<closure>>

0. /home/sysadmin/web/**REDACTED**/public_html/apps/richdocuments/lib/Middleware/WOPIMiddleware.php line 76
   OCA\Richdocuments\Db\WopiMapper->getWopiForToken("B80rHLs2rxjhCmH7lrkezsA7X3EZd6dj")
1. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php line 96
   OCA\Richdocuments\Middleware\WOPIMiddleware->beforeController(["OCA\\Richdocum ... "], "checkFileInfo")
2. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/Http/Dispatcher.php line 129
   OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController(["OCA\\Richdocum ... "], "checkFileInfo")
3. /home/sysadmin/web/**REDACTED**/public_html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Richdocum ... "], "checkFileInfo")
4. /home/sysadmin/web/**REDACTED**/public_html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Richdocume ... r", "checkFileInfo", ["OC\\AppFramewo ... "], ["30476_ocbk6qt4 ... "])
5. /home/sysadmin/web/**REDACTED**/public_html/lib/base.php line 1055
   OC\Route\Router->match("/apps/richdocum ... f")
6. /home/sysadmin/web/**REDACTED**/public_html/index.php line 36
   OC::handleRequest()

GET /index.php/apps/richdocuments/wopi/files/30476_ocbk6qt4plbf?access_token=B80rHLs2rxjhCmH7lrkezsA7X3EZd6dj&access_token_ttl=1681138942000
from xxx.xxx.xxx.xxx at 2023-04-10T05:07:25+00:00
```

**Comment by l3eochan** [comment]
I'm getting the exact same issue, collabora working on desktop but not on mobile. I don't have anything regarding this in the logs.

**Comment by enoch85** [comment]
This is fixed with the latest release (8.0.1).

**Comment by Happyfeet01** [comment]
Fixed with Collabora 8.0.1?

**Comment by l3eochan** [comment]
> Fixed with Collabora 8.0.1?

Yes I just installed the update and tried. It works now

**Comment by LokeYourLord** [comment]
> This is fixed with the latest release (8.0.1).

Can confirm, it's fixed. Updated to 8.0.1, then tried opening a document in the NextCloud mobile app. Loaded after a short while. 👍

**Comment by VPaulV** [comment]
I still have this problem in the desktop browser. Files simply won't open, and instead, I see a black screen until I press ESC. I'm running Nextcloud 26.0.1 and Nextcloud Office 8.0.1, and I've tried both self-hosted and demo servers. Unfortunately, there's absolutely nothing in the log file. Is there any way I can enable extra logging?
